os:
  - linux

language: cpp
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - kalakris-cmake
      - boost-latest
    packages:
      - gcc-4.9
      - g++-4.9
      - cmake
      - libboost1.55-all-dev

script:
 - export CC=gcc-4.9
 - export CXX=g++-4.9
 - mkdir build
 - cd build
 - cmake ..
 - make
