name: clang-format

on: [push, pull_request]

jobs:
  clang-format:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout dynarmic repo
      uses: actions/checkout@v2

    - uses: DoozyX/clang-format-lint-action@v0.15
      with:
        source: 'src tests'
        clangFormatVersion: 15
